<a href="https://colab.research.google.com/github/blockmoo/python_tutoring/blob/main/%EC%9C%A0%ED%98%B8%EC%84%A0_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

# 3.1.1 Create arrays

In [ ]:
#Create ndarrays from lists. note: every element must be the same type 
#(will be converted if possible)
data1 = [1, 2, 3, 4, 5]               # list
arr1 = np.array(data1)                # 1d array
type(arr1)                            # numpy.ndarray
data2 = [range(1, 5), range(5, 9)]    # list of lists
data2

[range(1, 5), range(5, 9)]

In [ ]:
arr2 = np.array(data2)                # 2d array
type(arr2)                            # numpy.ndarray
arr2.tolist()                         # convert array back to list
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Create a vector as a row
vector_row = np.array([1, 2, 3])

# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])
vector_column

array([[1],
       [2],
       [3]])

In [ ]:

# 2 x 3 matrix in Python    
A = ( [ 2, 5, 7 ],
      [ 4, 7, 9 ] )

# 3 x 4 matrix in Python where entries are floating numbers
B = ( [ 1.0, 3.5, 5.4, 7.9 ],
      [ 9.0, 2.5, 4.2, 3.6 ],
      [ 1.5, 3.2, 1.6, 6.5 ] )
type(A)  # tuple
type(B)  # tuple
print(A)
print(B)

([2, 5, 7], [4, 7, 9])
([1.0, 3.5, 5.4, 7.9], [9.0, 2.5, 4.2, 3.6], [1.5, 3.2, 1.6, 6.5])


In [ ]:
np.dot(A,B) # matrix의 곱 
type(np.dot(A,B))  # numpy.ndarray
np.dot(A,B)

array([[ 57.5,  41.9,  43. ,  79.3],
       [ 80.5,  60.3,  65.4, 115.3]])

In [ ]:
A2=[ [ 2, 5, 7 ],
      [ 4, 7, 9 ] ]

B2=[ [ 1.0, 3.5, 5.4, 7.9 ],
      [ 9.0, 2.5, 4.2, 3.6 ],
      [ 1.5, 3.2, 1.6, 6.5 ] ]
type(A2)  # list
type(B2)  # list
print(np.dot(A2,B2))
print(type(np.dot(A2,B2)))  # numpy.ndarray

[[ 57.5  41.9  43.   79.3]
 [ 80.5  60.3  65.4 115.3]]
<class 'numpy.ndarray'>


In [ ]:
# create special arrays
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.linspace(0, 1, 5)     # 0 to 1 (inclusive) with 5 points

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.logspace(0, 3, 4)     # 10^0 to 10^3 (inclusive) with 4 points

array([   1.,   10.,  100., 1000.])

In [ ]:
# arange is like range, except it returns an array (not a list)
int_array = np.arange(5)               #NumPy 버전의 range 명령이라고 볼 수 있다.
float_array = int_array.astype(float)

# 3.1.2 Examining arrays

In [ ]:
arr1.dtype    # int32
arr1.ndim     # 1
arr1.shape    # (5,) 
arr1.size     # 5 - total number of elements
len(arr1)     # 5 

arr2.dtype    # int32
arr2.ndim     # 2
arr2.shape    # (2, 4) - axis 0 is rows, axis 1 is columns
arr2.size     # 8 - total number of elements
len(arr2)     # 2 - size of first dimension (aka axis)


# 3.1.3 Reshaping

In [ ]:
arr = np.arange(10, dtype=float).reshape((2, 5))
print(arr.shape)   # (2,5)
print(arr.reshape(5, 2))
"""
[[0. 1.]
[2. 3.]
[4. 5.]
[6. 7.]
[8. 9.]]
"""

# Add an axis
a = np.array([0, 1])
a.shape                     #Out: (2,)
a.ndim                      #Out: 1
a_col = a[:, np.newaxis]    #행 부분에 np.newaxis를 입력시, 1D array를 row vector로 만든다.
                            #열 부분에 np.newaxis를 입력시, 1D array를 column vector로 만든다.
a_col.shape                 #Out: (2, 1)
print(a_col)
#Out:
#[[0]
#[1]]

a_col1 = a[np.newaxis,:] 
a_col1.shape                #Out: (1,2)
print(a_col1)               #Out: [[0 1]]
    
#or
a_col2 = a[:, None]
a_col2.shape                #Out: (2, 1)
print(a_col2)
#Out:
#[[0]
#[1]]

# Transpose
print(a_col.T)
#Out:
#[[0 1]]

b = np.array([[1, 2],
              [3, 4]], dtype=int)
print(b)
#[[1 2]
# [3 4]]

c = b[:, np.newaxis]
c.shape  # (2, 1, 2)
print(c)
#[[[1 2]]
# [[3 4]]]

print(c[1][0])         #[3 4]
print(c[1][0][1])      #4

# Flatten: always returns a flat copy of the orriginal array
arr_flt = arr.flatten()
arr_flt[0] = 33
print(arr_flt)
print(arr)

#Out:
#[33. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
#[[0. 1. 2. 3. 4.]
#[5. 6. 7. 8. 9.]]

#Ravel: returns a view of the original array whenever possible.
arr_flt2 = arr.ravel()
arr_flt2[0] = 33
print(arr_flt2)
print(arr)

#Out:
#[33. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
#[[33. 1. 2. 3. 4.]
#[ 5. 6. 7. 8. 9.]]


# 3.1.4 Stack arrays

In [ ]:
#Stack flat arrays in columns
a = np.array([0, 1])
b = np.array([2, 3])
ab = np.stack((a, b))
ab_t = np.stack((a, b)).T
print(ab)
#[[0 1]
#[2 3]]

print(ab_t)
#[[0 2]
#[1 3]]
    
# or
np.hstack((a[:, None], b[:, None]))

#Out:
#[[0 2]
#[1 3]]


# 3.1.5 Selection

In [ ]:
# Single item
arr = np.arange(10, dtype=float).reshape((2, 5))
arr[0]        # 0th element (slices like a list)
arr[0, 3]     # row 0, column 3: returns 3
arr[0][3]     # alternative syntax: returns 3

## Slicing
#Syntax: start:stop:step with start (default 0) stop (default last) step (default 1)
arr[0, :] # row 0: returns 1d array ([0, 1, 2, 3, 4])
arr[:, 0] # column 0: returns 1d array ([0, 5])
arr[:, :2] # columns strictly before index 2 (2 first columns)
arr[:, 2:] # columns after index 2 included
arr2 = arr[:, 1:4] # columns between index 1 (included) and 4 (excluded)
print(arr2)
#Out:
#[[1. 2. 3.]
#[6. 7. 8.]]

#Slicing returns a view (not a copy)
arr2[0, 0] = 33
print(arr2)
print(arr)
#Out:
#[[33. 2. 3.]
#[ 6. 7. 8.]]
#[[ 0. 33. 2. 3. 4.]
#[ 5. 6. 7. 8. 9.]]

#Row 0: reverse order
print(arr[0, ::-1])
# The rule of thumb here can be: in the context of lvalue indexing (i.e. the indices are␣
#placed in the left hand side value of an assignment), no view or copy of the array is␣
#created (because there is no need to). However, with regular values, the above rules␣
#for creating views does apply.

#Out:
#[ 4. 3. 2. 33. 0.]

##Fancy indexing: Integer or boolean array indexing

#Fancy indexing returns a copy not a view.

#Integer array indexing
arr = np.arange(10, dtype=float).reshape((2, 5))
arr2 = arr[:, [1,2,3]]  # return a copy  #arr[:, 1:4]와 차이가 있음 1:4
#print(arr2)
arr2[0, 0] = 44
print(arr2)
print(arr)

#Out:
#[[44.  2.  3.]
# [ 6.  7.  8.]]
#[[ 0. 1. 2. 3. 4.]
#[ 5. 6. 7. 8. 9.]]

#Boolean arrays indexing
arr = np.arange(10, dtype=float).reshape((2, 5))
arr2 = arr[arr > 5] # return a copy
print(arr2)     #[6. 7. 8. 9.]

arr2[0] = 44
print(arr2)     #[44.  7.  8.  9.]
print(arr)
#Out:
#[[0. 1. 2. 3. 4.]
# [5. 6. 7. 8. 9.]]

#However, in the context of lvalue indexing (left hand side value of an assignment) 
#Fancy authorizes the modification of the original array
arr = np.arange(10, dtype=float).reshape((2, 5))
arr[arr > 5] = 0
print(arr)
#Out:
#[[0. 1. 2. 3. 4.]
#[5. 0. 0. 0. 0.]]

#Boolean arrays indexing continues
names = np.array(['Bob', 'Joe', 'Will', 'Bob'])
names == 'Bob'                           # returns a boolean array,  #Out: array([ True, False, False,  True])
names[names != 'Bob']                    # logical selection,  #Out: array(['Joe', 'Will'], dtype='<U4')
(names == 'Bob') | (names == 'Will')     # keywords "and/or" don't work with boolean arrays,  #Out: array([ True, False,  True,  True])
names[names != 'Bob'] = 'Joe'            # assign based on a logical selection,  #Out: array(['Bob', 'Joe', 'Joe', 'Bob'], dtype='<U4')
np.unique(names)                         # set function,  #Out: array(['Bob', 'Joe'], dtype='<U4')

# 3.1.6 Vectorized operations

In [ ]:
nums = np.arange(5)
nums * 10                   # multiply each element by 10,  #Out: array([ 0, 10, 20, 30, 40])
nums = np.sqrt(nums)        # square root of each element, 
                            #Out: array([0., 1., 1.41421356, 1.73205081, 2. ]) 
np.ceil(nums)               # The ceil of the scalar x is the smallest integer i, such that i >= x.
                            #Out: array([0., 1., 2., 2., 2.])
np.isnan(nums)              # checks for NaN,  #Out: array([False, False, False, False, False])
nums + np.arange(5)         # add element-wise, Out: array([0., 2., 3.41421356, 4.73205081, 6.])
np.maximum(nums, np.array([1, -2, 3, -4, 5])) # compare element-wise and take maximum value element-wise

# Compute Euclidean distance between 2 vectors
vec1 = np.random.randn(10)
vec2 = np.random.randn(10)
dist = np.sqrt(np.sum((vec1 - vec2) ** 2))    #math.sqrt()

# math and stats
rnd = np.random.randn(4, 2)   # random normals in 4x2 array
rnd.mean()
rnd.std()
rnd.argmin()                  # index of minimum element
rnd.sum()
rnd.sum(axis=0)               # sum of columns  # "axis 0" goes along rows direction and "axis 1" goes along columns direction.
rnd.sum(axis=1)               # sum of rows

mat = np.array([[1, 2],[3,4]])
mat.argmin() 
mat.sum(axis=0)               # sum of columns # "axis 0" goes along rows direction and "axis 1" goes along columns direction.
mat.sum(axis=1)               # sum of rows

# methods for boolean arrays
(rnd > 0).sum()               # counts number of positive values
(rnd > 0).any()               # checks if any value is True
(rnd > 0).all()               # checks if all values are True

# random numbers
# random.seed(234)            # import random
np.random.seed(12234)         # Set the seed
np.random.rand(2, 3)          # 2 x 3 matrix in [0, 1]
np.random.randn(10)           # random normals (mean 0, sd 1)
np.random.randint(0, 2, 10)   # 10 randomly picked 0 or 1,  #numpy.random.randint(low, high=None, size=None, dtype='l')¶
# random.randint(a, b) returns a random integer N such that a <= N <= b.


# 3.1.7 Broadcasting

In [ ]:

## Rules
a = np.array([[0, 0, 0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])

b = np.array([0, 1, 2])
print(a + b)

#Out:
#[[ 0 1 2]
#[10 11 12]
#[20 21 22]
#[30 31 32]]

#=========================#
#======== Examples =======#
#=========================#
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
y1 = np.ones((5,), dtype=int)
z = np.ones((3,4))    # np.ones(3,4)  # TypeError: Cannot interpret '4' as a data type
# np.zeros

x.shape  #(4,)
y.shape  #(5,)
z.shape  #(3, 4)

x + y
# ValueError: operands could not be broadcast together with shapes (4,) (5,)

xx.shape   #(4, 1)
y.shape    #(5,)

(xx + y).shape  #(4, 5)
xx + y
#array([[ 1.,  1.,  1.,  1.,  1.],
#       [ 2.,  2.,  2.,  2.,  2.],
#       [ 3.,  3.,  3.,  3.,  3.],
#       [ 4.,  4.,  4.,  4.,  4.]])

(x + z).shape  #(3, 4)
x + z
#array([[ 1.,  2.,  3.,  4.],
#       [ 1.,  2.,  3.,  4.],
#       [ 1.,  2.,  3.,  4.]])

# Broadcasting provides a convenient way of taking the outer product (or any other outer operation) of two arrays. 
# The following example shows an outer addition operation of two 1-d arrays:

a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b
#array([[  1.,   2.,   3.],
#       [ 11.,  12.,  13.],
#       [ 21.,  22.,  23.],
#       [ 31.,  32.,  33.]])

#Shapes of operands A, B and result:
"""
A (2d array): 5 x 4
B (1d array): 1
Result (2d array): 5 x 4
A (2d array): 5 x 4
B (1d array): 4
Result (2d array): 5 x 4
A (3d array): 15 x 3 x 5
B (3d array): 15 x 1 x 5
Result (3d array): 15 x 3 x 5
A (3d array): 15 x 3 x 5
B (2d array): 3 x 5
Result (3d array): 15 x 3 x 5
A (3d array): 15 x 3 x 5
B (2d array): 3 x 1
Result (3d array): 15 x 3 x 5
"""

